In [1]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
x.resize((4,4))
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [2]:
y = np.delete(x,[0,1], axis=1)
y

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [3]:
z=np.delete(x,[0,1], axis=0)
z


array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [4]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
shuffled_indices = np.arange(len(x))
np.random.shuffle(shuffled_indices)
print(shuffled_indices)
x=x[shuffled_indices]
print(x)

[2 0 1 3]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [13 14 15 16]
 [ 9 10 11 12]]


In [17]:
x[[1,2]]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])